// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeAuctionAPI.Data;

#nullable disable

namespace PokeAuction.API.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20250718040713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokeAuctionAPI.Models.Evolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EvolutionTriggerId")
                        .HasColumnType("int");

                    b.Property<int>("EvolvedSpeciesId")
                        .HasColumnType("int");

                    b.Property<byte?>("GenderId")
                        .HasColumnType("tinyint");

                    b.Property<short?>("HeldItemId")
                        .HasColumnType("smallint");

                    b.Property<short?>("KnownMoveId")
                        .HasColumnType("smallint");

                    b.Property<string>("KnownMoveTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationId")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MinimumAffection")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MinimumBeauty")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("MinimumHappiness")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("MinimumLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("Natures")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte?>("NeedsOverworldRain")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("PartySpeciesId")
                        .HasColumnType("tinyint");

                    b.Property<string>("PartyTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("RelativePhysicalStats")
                        .HasColumnType("smallint");

                    b.Property<string>("TimeOfDay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("TradeSpeciesId")
                        .HasColumnType("smallint");

                    b.Property<int?>("TriggerItemId")
                        .HasColumnType("int");

                    b.Property<byte?>("TurnUpsideDown")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("evolution", (string)null);
                });

            modelBuilder.Entity("PokeAuctionAPI.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Cost")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Emote")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Page")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Separate")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Shard")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("PokeAuctionAPI.Models.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("Accuracy")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ContestEffectId")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ContestTypeId")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("DamageClassId")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EffectChance")
                        .HasColumnType("tinyint");

                    b.Property<short?>("EffectId")
                        .HasColumnType("smallint");

                    b.Property<byte>("GenerationId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("PP")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Power")
                        .HasColumnType("tinyint");

                    b.Property<short?>("Priority")
                        .HasColumnType("smallint");

                    b.Property<byte?>("SuperContestEffectId")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("TargetId")
                        .HasColumnType("tinyint");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("move", (string)null);
                });

            modelBuilder.Entity("PokeAuctionAPI.Models.Move_effect_prose", b =>
                {
                    b.Property<int>("MoveEffectId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<byte>("LocalLanguageId")
                        .HasColumnType("tinyint")
                        .HasColumnOrder(1);

                    b.Property<string>("Effect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortEffect")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MoveEffectId", "LocalLanguageId");

                    b.ToTable("move_effect_prose", (string)null);
                });

            modelBuilder.Entity("PokeAuctionAPI.Models.Pokemon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short?>("Abundance")
                        .HasColumnType("smallint")
                        .HasColumnName("abundance");

                    b.Property<byte?>("BaseAtk")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_atk");

                    b.Property<byte?>("BaseDef")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_def");

                    b.Property<byte?>("BaseHp")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_hp");

                    b.Property<byte?>("BaseSatk")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_satk");

                    b.Property<byte?>("BaseSdef")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_sdef");

                    b.Property<byte?>("BaseSpd")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_spd");

                    b.Property<byte?>("Catchable")
                        .HasColumnType("tinyint")
                        .HasColumnName("catchable");

                    b.Property<string>("Credit")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("credit");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<short?>("DexNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("dex_number");

                    b.Property<byte?>("Enabled")
                        .HasColumnType("tinyint")
                        .HasColumnName("enabled");

                    b.Property<string>("Event")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("event");

                    b.Property<long?>("EvoFrom")
                        .HasColumnType("bigint")
                        .HasColumnName("evo_from");

                    b.Property<short?>("EvoMega")
                        .HasColumnType("smallint")
                        .HasColumnName("evo_mega");

                    b.Property<short?>("EvoMegaX")
                        .HasColumnType("smallint")
                        .HasColumnName("evo_mega_x");

                    b.Property<short?>("EvoMegaY")
                        .HasColumnType("smallint")
                        .HasColumnName("evo_mega_y");

                    b.Property<string>("EvoTo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("evo_to");

                    b.Property<string>("FormItem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("form_item");

                    b.Property<short?>("GenderRate")
                        .HasColumnType("smallint")
                        .HasColumnName("gender_rate");

                    b.Property<bool?>("HasGenderDifferences")
                        .HasColumnType("bit")
                        .HasColumnName("has_gender_differences");

                    b.Property<short?>("Height")
                        .HasColumnType("smallint")
                        .HasColumnName("height");

                    b.Property<string>("IsForm")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("is_form");

                    b.Property<byte?>("Legendary")
                        .HasColumnType("tinyint")
                        .HasColumnName("legendary");

                    b.Property<byte?>("Mythical")
                        .HasColumnType("tinyint")
                        .HasColumnName("mythical");

                    b.Property<string>("NameDe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name_de");

                    b.Property<string>("NameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameEn2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name_en2");

                    b.Property<string>("NameFr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name_fr");

                    b.Property<string>("NameJa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name_ja");

                    b.Property<string>("NameJaR")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name_ja_r");

                    b.Property<string>("NameJaT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name_ja_t");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("region");

                    b.Property<string>("Slug")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("slug");

                    b.Property<string>("Type0")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type_0");

                    b.Property<string>("Type1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type_1");

                    b.Property<string>("UltraBeast")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ultra_beast");

                    b.Property<short?>("Weight")
                        .HasColumnType("smallint")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("pokemon", (string)null);
                });

            modelBuilder.Entity("PokeAuctionAPI.Models.Pokemon_Move", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<byte>("VersionGroupId")
                        .HasColumnType("tinyint")
                        .HasColumnOrder(1);

                    b.Property<short>("MoveId")
                        .HasColumnType("smallint")
                        .HasColumnOrder(2);

                    b.Property<byte>("PokemonMoveMethodId")
                        .HasColumnType("tinyint")
                        .HasColumnOrder(3);

                    b.Property<byte?>("Level")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Order")
                        .HasColumnType("tinyint");

                    b.HasKey("PokemonId", "VersionGroupId", "MoveId", "PokemonMoveMethodId");

                    b.ToTable("pokemon_move", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
