// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeAuctionAPI.Data;

#nullable disable

namespace PokeAuction.API.Migrations
{
    [DbContext(typeof(PokeContext))]
    [Migration("20250716051523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokeAuctionAPI.Models.Pokemon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Abundance")
                        .HasColumnType("smallint")
                        .HasColumnName("abundance");

                    b.Property<byte>("BaseAtk")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_atk");

                    b.Property<byte>("BaseDef")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_def");

                    b.Property<byte>("BaseHp")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_hp");

                    b.Property<byte>("BaseSatk")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_satk");

                    b.Property<byte>("BaseSdef")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_sdef");

                    b.Property<byte>("BaseSpd")
                        .HasColumnType("tinyint")
                        .HasColumnName("base_spd");

                    b.Property<byte>("Catchable")
                        .HasColumnType("tinyint")
                        .HasColumnName("catchable");

                    b.Property<string>("Credit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("credit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<short>("DexNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("dex_number");

                    b.Property<byte>("Enabled")
                        .HasColumnType("tinyint")
                        .HasColumnName("enabled");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("event");

                    b.Property<long?>("EvoFrom")
                        .HasColumnType("bigint")
                        .HasColumnName("evo_from");

                    b.Property<short?>("EvoMega")
                        .HasColumnType("smallint")
                        .HasColumnName("evo_mega");

                    b.Property<short?>("EvoMegaX")
                        .HasColumnType("smallint")
                        .HasColumnName("evo_mega_x");

                    b.Property<short?>("EvoMegaY")
                        .HasColumnType("smallint")
                        .HasColumnName("evo_mega_y");

                    b.Property<string>("EvoTo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("evo_to");

                    b.Property<string>("FormItem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("form_item");

                    b.Property<short>("GenderRate")
                        .HasColumnType("smallint")
                        .HasColumnName("gender_rate");

                    b.Property<bool>("HasGenderDifferences")
                        .HasColumnType("bit")
                        .HasColumnName("has_gender_differences");

                    b.Property<short>("Height")
                        .HasColumnType("smallint")
                        .HasColumnName("height");

                    b.Property<string>("IsForm")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("is_form");

                    b.Property<byte?>("Legendary")
                        .HasColumnType("tinyint")
                        .HasColumnName("legendary");

                    b.Property<byte?>("Mythical")
                        .HasColumnType("tinyint")
                        .HasColumnName("mythical");

                    b.Property<string>("NameDe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_de");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameEn2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_en2");

                    b.Property<string>("NameFr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_fr");

                    b.Property<string>("NameJa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_ja");

                    b.Property<string>("NameJaR")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_ja_r");

                    b.Property<string>("NameJaT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_ja_t");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slug");

                    b.Property<string>("Type0")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type_0");

                    b.Property<string>("Type1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type_1");

                    b.Property<string>("UltraBeast")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ultra_beast");

                    b.Property<short>("Weight")
                        .HasColumnType("smallint")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("pokemon", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
